version: '3.8'

services:
  php-composer:
    image: composer
    container_name: php-composer
    volumes:
      - .:/app

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
